services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: "docker.io/juanlarraya/backend:0.1.0"
    platform: linux/amd64
    volumes:
      - my-volume:/root/.my-volume              # Persistent per-machine storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    ports:
      - "3000:3000"

volumes:
  my-volume:

